name: Prism Release Workflow
on: [pull_request, workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: prism-release
          path: app/build/outputs/apk/release/app-release.apk
